import './home.scss'
import {Box} from "@mui/material";
import rocket from "../../assets/img/rocket.webp";
import * as React from "react";

export function Home(){
    return (
        <div className="container pt-5">
            <div className="headline-root">
                <Box className="headline-left-box">
                    <section className="main-info">
                        <div>
                            <p>What is Oracle Finance?</p>
                            <p>
                                A Financial Platform To Facilitate
                                <br />A Multitude Of Cryptocurrency
                                <br />
                                Investing
                            </p>
                            <div>
                                <p>
                                    Oracle is a community-governed, yield generating
                                    <br />
                                    deflationary protocol that is built for sustainable
                                    <br />
                                    growth in any market condition
                                </p>
                            </div>
                        </div>
                    </section>
                </Box>
                <Box className="headline-right-box">
                    <img
                        src = {rocket}
                        alt = "oracle-finance"
                        className = "headline-img"
                    />
                </Box>
            </div>


            <section className="project-selection-text-container d-flex justify-content-center">
                <p>WHY ORACLE LAUNCHPAD?</p>
            </section>

            <section id="projects" className="mt-5 project-selection-container d-flex p-3 align-items-center">
                <div className="project-selection-image d-none d-sm-block"></div>
                <div className="project-selection-text p-5">
                    <p>Oracle Ecosystem</p>
                    <p>Oracle Finance will power many platforms and applications which will grow the entire ecosystem
                        and help bring more profits to the treasury</p>
                </div>
            </section>

            <section className="mt-5 detail-report-container d-flex p-3 align-items-center">
                <div className="detail-report-text p-5">
                    <p>Oracle Capital</p>
                    <p>A percentage of treasury is allocated to Venture Funds, Liquid Token Funds, and Yield Farming
                        for better capital efficiency and rewards for the entire ecosystem and its users.</p>
                </div>
                <div className="detail-report-image d-none d-sm-block"></div>
            </section>

            <section className="mt-5 tier-system-container d-flex p-3 align-items-center">
                <div className="tier-system-image d-none d-sm-block"></div>
                <div className="tier-system-text p-5">
                    <p>Oracle Ecosystem</p>
                    <p>Oracle Finance will power many platforms and applications which will grow the entire ecosystem
                        and help bring more profits to the treasury</p>
                </div>
            </section>

            <section className="project-selection-text-container d-flex justify-content-center">
                <p>FOR PROJECT</p>
            </section>


            <div className="mt-5 cards-container">
                <div className="p-5 mt-3 flex-grow-1 me-3">
                    <div/>
                    <p>Staking & Bonding</p>
                    <p>Primary ways for users to build wealth. Users can purchase ORCL at discounted price
                        via bonding and/or can stake ORCL to receive passive yields</p>
                </div>
                <div className="p-5 mt-3 flex-grow-1 me-3">
                    <div/>
                    <p>Treasury</p>
                    <p>Treasury is the engine of Oracle Finance and backs overall floor price, which ensures underlying
                        price is independent of market volatility</p>
                </div>
                <div className="p-5 mt-3 flex-grow-1">
                    <div />
                    <p>Rewards Distribution</p>
                    <p>The total profit generated by the protocol is distributed to all stakers in stable coins,
                        thus generating a passive yield with relatively low risks</p>
                </div>
            </div>
        </div>
        )
}