import './home.scss'
import {Box, Link} from "@mui/material";
import rocket from "../../assets/img/rocket.webp";
import * as React from "react";

export function Home(){
    return (
        <div className="container pt-5">
            <div className="headline-root">
                <Box className="headline-left-box">
                    <section className="main-info">
                        <div>
                            <p>What is Oracle LaunchPad?</p>
                            <p>
                                Next Generation of effective fundraising.
                            </p>
                            <div>
                                <p>
                                    Breaking barriers for small investors to the IDO platform with a no-tier system.
                                    We aim to provide a high-quality investment opportunities for our investors.
                                </p>
                            </div>
                        </div>
                    </section>
                    <div className="project-button-div mt-3 mb-3">
                        <Link className="project-button" href = "/projects" underline="none">
                            Projects
                        </Link>
                    </div>
                </Box>
                <Box className="headline-right-box">
                    <img
                        src = {rocket}
                        alt = "oracle-finance"
                        className = "headline-img"
                    />
                </Box>
            </div>


            <section className="project-selection-text-container d-flex justify-content-center">
                <p>WHY ORACLE LAUNCHPAD?</p>
            </section>

            <section id="projects" className="mt-5 container-with-image d-flex p-3 align-items-center">
                <div className="section-text p-5">
                    <p>Project Selection Criteria</p>
                    <p>Project launching IDO on Oracle LaunchPad needs to meet specific criteria in terms of
                        idea, potential, project development and overall security.
                    </p>
                </div>
                <div className="section-image d-none d-sm-block"></div>
            </section>

            <section className="mt-5 container-with-image d-flex p-3 align-items-center">
                <div className="section-image d-none d-sm-block"></div>
                <div className="section-text p-5">
                    <p>Detailed Report Generation</p>
                    <p>Our teams of experts will evaluate each and every project and prepare a detailed report to
                        help investors make an informed decision.
                    </p>
                </div>
            </section>

            <section className="mt-5 container-with-image d-flex p-3 align-items-center">
                <div className="section-text p-5">
                    <p>Tierless System</p>
                    <p>Unlike other launchpads, Oracle LaunchPad does not have a tier system.
                        Investors who have staked ORFI tokens can take part in IDOs</p>
                </div>
                <div className="section-image d-none d-sm-block"></div>
            </section>

            {/*<section className="project-selection-text-container d-flex justify-content-center">*/}
            {/*    <p>FOR PROJECTS</p>*/}
            {/*</section>*/}

            {/*<div className="mt-5 cards-container">*/}
            {/*    <div className="p-5 mt-3 flex-grow-1 me-3">*/}
            {/*        <div/>*/}
            {/*        <p>Private Sale</p>*/}
            {/*        <p>Primary ways for users to build wealth. Users can purchase ORCL at discounted price*/}
            {/*            via bonding and/or can stake ORCL to receive passive yields</p>*/}
            {/*    </div>*/}
            {/*    <div className="p-5 mt-3 flex-grow-1 me-3">*/}
            {/*        <div/>*/}
            {/*        <p>Treasury</p>*/}
            {/*        <p>Treasury is the engine of Oracle Finance and backs overall floor price, which ensures underlying*/}
            {/*            price is independent of market volatility</p>*/}
            {/*    </div>*/}
            {/*    <div className="p-5 mt-3 flex-grow-1">*/}
            {/*        <div />*/}
            {/*        <p>Rewards Distribution</p>*/}
            {/*        <p>The total profit generated by the protocol is distributed to all stakers in stable coins,*/}
            {/*            thus generating a passive yield with relatively low risks</p>*/}
            {/*    </div>*/}
            {/*</div>*/}
        </div>
        )
}